/* EcoTravel Week 3 - accessible interaction with defensive error handling */
"use strict";
document.addEventListener("DOMContentLoaded",()=>{try{initializeNavigation();initializeAccordion();initializeCurrentYear()}catch(error){console.error("EcoTravel initialization error:",error);announce("Some interactive features could not be initialized. The page content remains available.")}});
function initializeNavigation(){const toggle=document.querySelector(".menu-toggle"),nav=document.getElementById("primary-nav");if(!toggle||!nav)return;toggle.addEventListener("click",()=>{const open=toggle.getAttribute("aria-expanded")==="true";toggle.setAttribute("aria-expanded",String(!open));nav.classList.toggle("is-open",!open);if(!open){const first=nav.querySelector("a");if(first&&window.matchMedia("(max-width: 850px)").matches)first.focus()}});nav.addEventListener("click",e=>{if(e.target.matches("a")){toggle.setAttribute("aria-expanded","false");nav.classList.remove("is-open")}})}
function initializeAccordion(){const accordion=document.querySelector("[data-accordion]");if(!accordion)return;const triggers=accordion.querySelectorAll(".accordion-trigger");if(!triggers.length)return;triggers.forEach(trigger=>trigger.addEventListener("click",()=>{const expanded=trigger.getAttribute("aria-expanded")==="true";closeAllAccordionItems(triggers);if(!expanded)openAccordionItem(trigger)}))}
function openAccordionItem(trigger){const panel=document.getElementById(trigger.getAttribute("aria-controls"));if(!panel)return;trigger.setAttribute("aria-expanded","true");panel.hidden=false;announce(trigger.textContent.trim()+" expanded.")}
function closeAllAccordionItems(triggers){triggers.forEach(trigger=>{const panel=document.getElementById(trigger.getAttribute("aria-controls"));trigger.setAttribute("aria-expanded","false");if(panel)panel.hidden=true})}
function initializeCurrentYear(){const year=document.getElementById("current-year");if(year)year.textContent=new Date().getFullYear()}
function announce(message){const status=document.getElementById("status-message");if(!status)return;status.textContent="";setTimeout(()=>{status.textContent=message},50)}
